apiVersion: apps/v1
kind: Deployment
metadata:
  name: ac_bend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ac_bend
  template:
    metadata:
      labels:
        app:  ac_bend
    spec:
      containers:
        - name: ac_bend
          image: "gcr.io/google-samples/hello-go-gke:1.0"
          ports:
          - name: http
            containerPort: 80