apiVersion: apps/v1
kind: Deployment
metadata:
  name: ac_fend
spec:
  restartPolicy: Always
  replicas: 1
  selector:
    matchLabels:
      app: ac_fend
  template:
    metadata:
      labels:
        app: ac_fend
    spec:
      containers:
        - name: ac_fend
          image: "gcr.io/google-samples/hello-frontend:1.0"
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx","-s","quit"]